### ISSUE TITLE
Add a version

### ISSUE THREAD

**Issue by halilim** [vzaar/vzaar-jquery#1]
Many build tools require a version to operate by default, using the `master` directly is sometimes not supported at all (in my instance it's Rails Assets BTW).

So I propose adding a version, even if it's just `0.1.0`.

**Comment by revdan** [comment]
Thanks for the suggestion :)

I've created a release on here tagged with `v0.1.0`. Please let me know if it works okay for you and I'll close this down.

**Comment by halilim** [comment]
Thanks, it's all OK now :)

**Comment by revdan** [comment]
Glad to hear it :+1:
